services:
  postgres:
    image: postgres:15-alpine
    container_name: buzzly-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      # Use container env at runtime; $$ escapes for Compose so the shell in the container sees $POSTGRES_*
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: buzzly-backend
    env_file:
      - backend/.env            # created by the workflow from BACKEND_ENV_DEV
    environment:
      DB_HOST: postgres         # service name reachable on the compose network
      DB_PORT: 5432
      PORT: 5000
      PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: buzzly-frontend
    depends_on:
      - backend
    ports:
      - "80:80"                 # if 80 is busy on the host, change to "8080:80"

volumes:
  postgres_data:
