services:
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env   # okay for testing only
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
