name: smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ensure LF for shell scripts (protects against CRLF pushes)
      - name: Normalize line endings for .sh
        run: |
          git config core.autocrlf false
          find . -type f -name "*.sh" -print0 | xargs -0 sed -i 's/\r$//'

      # make sure entrypoint is executable (safety net)
      - name: chmod scripts
        run: chmod +x backend/entrypoint.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend
        run: docker build -t test-backend:ci ./backend

      - name: Build frontend
        run: docker build -t test-frontend:ci ./frontend

      - name: Compose build (full stack)
        run: docker compose -f docker-compose.yml build
