name: Smoke
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: [self-hosted, linux, x64, local, dind]
    steps:
      - uses: actions/checkout@v4

      - name: Show runner details
        run: |
          echo "Runner: $(hostname)"
          uname -a

      - name: Wait for Docker daemon
        shell: bash
        run: |
          echo "Waiting for Docker to be ready..."
          for i in {1..30}; do
            if docker info >/dev/null 2>&1; then
              echo "Docker is up."
              exit 0
            fi
            sleep 2
          done
          echo "Docker failed to start in time"; exit 1

      - name: Docker sanity
        run: |
          docker info
          docker run --rm hello-world
