name: Host Runner Smoke

on:
  workflow_dispatch:    # run it manually
  push:
    branches: [ main ]  # optional: runs on every push to main

jobs:
  ping-runner:
    # must match your runner's labels
    runs-on: [self-hosted, linux, x64, host]
    timeout-minutes: 10

    steps:
      - name: Show runner basics
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Runner: $RUNNER_NAME"
          echo "Labels: $RUNNER_OS $RUNNER_ARCH (custom: host)"
          echo "Working dir: $GITHUB_WORKSPACE"
          uname -a
          whoami
          df -h
          free -m || true

      - name: Check network
        run: |
          ping -c 2 github.com || true
          curl -sI https://api.github.com | head -n 1

      - name: Create and read a file in workspace
        run: |
          echo "hello from $(hostname) at $(date)" > hello.txt
          ls -la
          cat hello.txt

      - name: Checkout repo (sanity)
        uses: actions/checkout@v4
