name: Smoke

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: [self-hosted, linux, x64, local, dind]
    steps:
      - uses: actions/checkout@v4

      - name: Echo host
        run: echo "Hello from $(hostname)"

      - name: Docker check
        run: |
          docker info
          docker run --rm hello-world
