name: Smoke
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: [self-hosted, linux, x64, local, dind]

    # Start a sidecar Docker daemon
    services:
      docker:
        image: docker:24-dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""
        ports:
          - 2375:2375   # not strictly required

    env:
      DOCKER_HOST: tcp://docker:2375

    steps:
      - uses: actions/checkout@v4

      - name: Sanity
        run: |
          docker version
          docker run --rm hello-world

