name: Smoke
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: [self-hosted, linux, x64, host]  # matches the labels you set
    steps:
      - uses: actions/checkout@v4
      - name: Runner details
        run: |
          echo "Runner: $(hostname)"
          uname -a
      - name: Docker sanity (host Docker)
        run: |
          docker version
          docker run --rm hello-world
